import {
  Region,
  Area,
  Branch,
  Employee,
  User,
  Customer,
  Transaction,
  Approval,
  Notification,
  AuditLog,
  LoginLog,
  SystemSettings
} from '../types';

export const INITIAL_REGIONS: Region[] = [
  { id: 'reg_01', code: 'REG-NCR', name: 'National Capital Region (NCR)', managerName: 'Vicente Mendoza', status: true },
  { id: 'reg_02', code: 'REG-VII', name: 'Central Visayas (Region VII)', managerName: 'Juan Dela Cruz', status: true },
  { id: 'reg_03', code: 'REG-VI', name: 'Western Visayas (Region VI)', managerName: 'Elena Ramos', status: true },
  { id: 'reg_04', code: 'REG-XI', name: 'Southern Mindanao (Region XI)', managerName: 'Arturo Silvano', status: true },
];

export const INITIAL_AREAS: Area[] = [
  { id: 'area_01', regionId: 'reg_02', code: 'AREA-CEB-01', name: 'Cebu Metro Central', managerName: 'Maria Santos', status: true },
  { id: 'area_02', regionId: 'reg_02', code: 'AREA-CEB-02', name: 'Mandaue & Lapu-Lapu Coast', managerName: 'Kenneth Yap', status: true },
  { id: 'area_03', regionId: 'reg_01', code: 'AREA-NCR-01', name: 'Makati Financial District', managerName: 'Lourdes Aquino', status: true },
  { id: 'area_04', regionId: 'reg_01', code: 'AREA-NCR-02', name: 'Quezon City Commercial', managerName: 'Ramon Castillo', status: true },
  { id: 'area_05', regionId: 'reg_04', code: 'AREA-DVO-01', name: 'Davao Downtown Core', managerName: 'Felipe Alcantara', status: true },
];

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'br_01',
    areaId: 'area_01',
    code: 'BR001-CEB',
    name: 'Cebu Main Operations Hub',
    address: 'Osmeña Blvd cor. P. del Rosario St.',
    city: 'Cebu City',
    province: 'Cebu',
    contact: '+63 (32) 255-8901',
    email: 'cebu.main@zebra-enterprise.internal',
    managerId: 'emp_03',
    managerName: 'Roberto Tan',
    status: 'ACTIVE',
  },
  {
    id: 'br_02',
    areaId: 'area_01',
    code: 'BR002-JON',
    name: 'Jones Avenue Branch',
    address: 'Gen. Maxilom Avenue',
    city: 'Cebu City',
    province: 'Cebu',
    contact: '+63 (32) 412-3320',
    email: 'jones.ave@zebra-enterprise.internal',
    managerId: 'emp_09',
    managerName: 'Corazon Velez',
    status: 'ACTIVE',
  },
  {
    id: 'br_03',
    areaId: 'area_01',
    code: 'BR003-CLN',
    name: 'Colon Heritage Branch',
    address: 'Colon Street Downtown',
    city: 'Cebu City',
    province: 'Cebu',
    contact: '+63 (32) 231-9044',
    email: 'colon.heritage@zebra-enterprise.internal',
    managerId: 'emp_10',
    managerName: 'Dante Ocampo',
    status: 'ACTIVE',
  },
  {
    id: 'br_04',
    areaId: 'area_03',
    code: 'BR004-MKT',
    name: 'Makati Ayala CBD Branch',
    address: 'Ayala Triangle Plaza, Tower 2',
    city: 'Makati City',
    province: 'Metro Manila',
    contact: '+63 (2) 8812-7000',
    email: 'makati.ayala@zebra-enterprise.internal',
    managerId: 'emp_07',
    managerName: 'Patricia Gomez',
    status: 'ACTIVE',
  },
  {
    id: 'br_05',
    areaId: 'area_03',
    code: 'BR005-BND',
    name: 'Buendia Transit Hub Branch',
    address: 'Gil Puyat Ave cor. Taft Ave',
    city: 'Pasay / Makati Border',
    province: 'Metro Manila',
    contact: '+63 (2) 8844-5511',
    email: 'buendia.hub@zebra-enterprise.internal',
    managerId: 'emp_11',
    managerName: 'Rodolfo Sy',
    status: 'ACTIVE',
  },
  {
    id: 'br_06',
    areaId: 'area_04',
    code: 'BR006-CBO',
    name: 'Cubao Integrated Terminal Branch',
    address: 'Aurora Blvd cor. EDSA',
    city: 'Quezon City',
    province: 'Metro Manila',
    contact: '+63 (2) 8911-2244',
    email: 'cubao.terminal@zebra-enterprise.internal',
    managerId: 'emp_12',
    managerName: 'Grace Tolentino',
    status: 'ACTIVE',
  },
  {
    id: 'br_07',
    areaId: 'area_05',
    code: 'BR007-BJD',
    name: 'Bajada Commercial Branch',
    address: 'J.P. Laurel Ave, Bajada',
    city: 'Davao City',
    province: 'Davao del Sur',
    contact: '+63 (82) 221-8899',
    email: 'davao.bajada@zebra-enterprise.internal',
    managerId: 'emp_13',
    managerName: 'Emmanuel Cruz',
    status: 'ACTIVE',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp_01',
    employeeNo: 'EMP00001',
    firstName: 'Juan',
    middleName: 'Santos',
    lastName: 'Dela Cruz',
    position: 'Regional Operations Director',
    department: 'Executive Operations',
    contact: '+63 917 800 1101',
    email: 'juan.delacruz@zebra-enterprise.com',
    address: 'Lahug, Cebu City',
    dateHired: '2020-03-15',
    branchId: 'br_01',
    status: 'ACTIVE',
  },
  {
    id: 'emp_02',
    employeeNo: 'EMP00002',
    firstName: 'Maria',
    middleName: 'Teresa',
    lastName: 'Santos',
    position: 'Area Operations Manager',
    department: 'Branch Supervision',
    contact: '+63 918 555 2202',
    email: 'maria.santos@zebra-enterprise.com',
    address: 'Banilad, Cebu City',
    dateHired: '2021-06-01',
    branchId: 'br_01',
    status: 'ACTIVE',
  },
  {
    id: 'emp_03',
    employeeNo: 'EMP00003',
    firstName: 'Roberto',
    middleName: 'Carlos',
    lastName: 'Tan',
    position: 'Branch Manager',
    department: 'Retail Banking & Remittance',
    contact: '+63 920 333 4403',
    email: 'roberto.tan@zebra-enterprise.com',
    address: 'Guadalupe, Cebu City',
    dateHired: '2022-01-10',
    branchId: 'br_01',
    status: 'ACTIVE',
  },
  {
    id: 'emp_04',
    employeeNo: 'EMP00004',
    firstName: 'Ana',
    middleName: 'Lou',
    lastName: 'Reyes',
    position: 'Senior Operations Teller',
    department: 'Counter Operations',
    contact: '+63 917 111 8804',
    email: 'ana.reyes@zebra-enterprise.com',
    address: 'Mambaling, Cebu City',
    dateHired: '2023-04-18',
    branchId: 'br_01',
    status: 'ACTIVE',
  },
  {
    id: 'emp_05',
    employeeNo: 'EMP00005',
    firstName: 'Gabriel',
    middleName: 'Vicente',
    lastName: 'Lim',
    position: 'Senior Compliance Auditor',
    department: 'Internal Audit & Risk',
    contact: '+63 919 444 9905',
    email: 'gabriel.lim@zebra-enterprise.com',
    address: 'Cebu I.T. Park, Cebu City',
    dateHired: '2021-11-20',
    branchId: 'br_01',
    status: 'ACTIVE',
  },
  {
    id: 'emp_06',
    employeeNo: 'EMP00006',
    firstName: 'Eduardo',
    middleName: 'Perez',
    lastName: 'Flores',
    position: 'Enterprise Systems Administrator',
    department: 'Information Technology',
    contact: '+63 922 777 3306',
    email: 'eduardo.flores@zebra-enterprise.com',
    address: 'Mandaue City, Cebu',
    dateHired: '2019-08-01',
    branchId: 'br_01',
    status: 'ACTIVE',
  },
  {
    id: 'emp_07',
    employeeNo: 'EMP00007',
    firstName: 'Patricia',
    middleName: 'Isabel',
    lastName: 'Gomez',
    position: 'Branch Manager',
    department: 'Retail Banking & Remittance',
    contact: '+63 917 222 5507',
    email: 'patricia.gomez@zebra-enterprise.com',
    address: 'Bel-Air, Makati City',
    dateHired: '2022-05-12',
    branchId: 'br_04',
    status: 'ACTIVE',
  },
  {
    id: 'emp_08',
    employeeNo: 'EMP00008',
    firstName: 'Miguel',
    middleName: 'Angel',
    lastName: 'Bautista',
    position: 'Counter Operations Associate',
    department: 'Counter Operations',
    contact: '+63 918 333 6608',
    email: 'miguel.bautista@zebra-enterprise.com',
    address: 'Poblacion, Makati City',
    dateHired: '2024-02-01',
    branchId: 'br_04',
    status: 'ACTIVE',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_super',
    username: 'superadmin',
    role: 'SUPER_ADMIN',
    roleId: 'role_super_admin',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-03T08:45:10Z',
    failedAttempts: 0,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'usr_admin',
    employeeId: 'emp_06',
    username: 'EMP00006',
    role: 'ADMIN',
    roleId: 'role_admin',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-03T07:30:22Z',
    failedAttempts: 0,
    createdAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'usr_reg',
    employeeId: 'emp_01',
    username: 'EMP00001',
    role: 'REGIONAL_MANAGER',
    roleId: 'role_reg_mgr',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-02T16:12:00Z',
    failedAttempts: 0,
    createdAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 'usr_area',
    employeeId: 'emp_02',
    username: 'EMP00002',
    role: 'AREA_MANAGER',
    roleId: 'role_area_mgr',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-03T06:55:00Z',
    failedAttempts: 0,
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'usr_branch',
    employeeId: 'emp_03',
    username: 'EMP00003',
    role: 'BRANCH_MANAGER',
    roleId: 'role_branch_mgr',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-03T08:15:30Z',
    failedAttempts: 0,
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'usr_teller',
    employeeId: 'emp_04',
    username: 'EMP00004',
    role: 'EMPLOYEE',
    roleId: 'role_employee',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-03T08:00:00Z',
    failedAttempts: 0,
    createdAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'usr_audit',
    employeeId: 'emp_05',
    username: 'EMP00005',
    role: 'AUDITOR',
    roleId: 'role_auditor',
    status: 'ACTIVE',
    lastLoginAt: '2026-10-02T14:40:00Z',
    failedAttempts: 0,
    createdAt: '2025-02-15T00:00:00Z',
  },
  {
    id: 'usr_locked',
    employeeId: 'emp_08',
    username: 'EMP00008',
    role: 'EMPLOYEE',
    roleId: 'role_employee',
    status: 'LOCKED',
    lastLoginAt: '2026-09-30T10:15:00Z',
    failedAttempts: 5,
    lockedUntil: '2026-10-03T18:00:00Z',
    createdAt: '2025-04-10T00:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cus_01',
    customerNo: 'CUS000101',
    firstName: 'Mateo',
    middleName: 'Silva',
    lastName: 'Rossi',
    contact: '+63 917 555 9011',
    email: 'mateo.rossi@email.ph',
    address: 'Unit 14B, Horizon Residences, Cebu City',
    idType: 'Philippine Passport',
    idNumber: 'P8921820B',
    kycVerified: true,
    status: true,
    createdAt: '2025-02-10T09:12:00Z',
  },
  {
    id: 'cus_02',
    customerNo: 'CUS000102',
    firstName: 'Carmen',
    middleName: 'Duran',
    lastName: 'Villanueva',
    contact: '+63 920 444 3122',
    email: 'carmen.v@email.ph',
    address: '45 Manga St., Guadalupe, Cebu City',
    idType: 'Driver License',
    idNumber: 'N03-18-992120',
    kycVerified: true,
    status: true,
    createdAt: '2025-03-01T11:45:00Z',
  },
  {
    id: 'cus_03',
    customerNo: 'CUS000103',
    firstName: 'Danilo',
    middleName: 'Jose',
    lastName: 'Soriano',
    contact: '+63 919 777 4433',
    email: 'danilo.soriano@email.ph',
    address: '782 Escolta St., Binondo, Manila',
    idType: 'National ID (PhilSys)',
    idNumber: '8910-2291-0021-4412',
    kycVerified: true,
    status: true,
    createdAt: '2025-04-12T14:30:00Z',
  },
  {
    id: 'cus_04',
    customerNo: 'CUS000104',
    firstName: 'Liezel',
    middleName: 'Marie',
    lastName: 'Mercado',
    contact: '+63 918 222 7744',
    email: 'liezel.mercado@email.ph',
    address: 'Brgy. San Antonio, Makati City',
    idType: 'UMID',
    idNumber: '0111-928192-3',
    kycVerified: true,
    status: true,
    createdAt: '2025-05-20T10:00:00Z',
  },
  {
    id: 'cus_05',
    customerNo: 'CUS000105',
    firstName: 'Antonio',
    middleName: 'Ramon',
    lastName: 'Pangilinan',
    contact: '+63 922 999 1155',
    email: 'antonio.p@email.ph',
    address: 'Matina Crossing, Davao City',
    idType: 'Voter ID',
    idNumber: 'DVO-2019-99411',
    kycVerified: false,
    status: true,
    createdAt: '2025-06-15T15:20:00Z',
  },
  {
    id: 'cus_06',
    customerNo: 'CUS000106',
    firstName: 'Rowena',
    middleName: 'Castro',
    lastName: 'Alcantara',
    contact: '+63 917 333 8866',
    email: 'rowena.alcantara@email.ph',
    address: 'Subangdaku, Mandaue City',
    idType: 'Philippine Passport',
    idNumber: 'P4410921A',
    kycVerified: true,
    status: true,
    createdAt: '2025-07-01T08:50:00Z',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_01',
    transactionNo: 'TXN-20261003-000101',
    customerId: 'cus_01',
    branchId: 'br_01',
    employeeId: 'emp_04',
    type: 'REMITTANCE_SEND',
    amount: 8500,
    fee: 150,
    total: 8650,
    status: 'COMPLETED',
    referenceNo: 'REF-CEB-882109',
    notes: 'Domestic express remittance to Iloilo City receiver.',
    createdAt: '2026-10-03T07:15:00Z',
    completedAt: '2026-10-03T07:18:22Z',
  },
  {
    id: 'txn_02',
    transactionNo: 'TXN-20261003-000102',
    customerId: 'cus_02',
    branchId: 'br_01',
    employeeId: 'emp_04',
    type: 'FOREIGN_EXCHANGE',
    amount: 45000,
    fee: 250,
    total: 45250,
    status: 'PENDING',
    referenceNo: 'FX-USD-99012',
    notes: 'Exchange USD 800 at 56.25 PHP rate. High-value transaction requires Manager approval.',
    requiresApproval: true,
    approvalId: 'app_01',
    createdAt: '2026-10-03T08:10:00Z',
  },
  {
    id: 'txn_03',
    transactionNo: 'TXN-20261003-000103',
    customerId: 'cus_03',
    branchId: 'br_04',
    employeeId: 'emp_08',
    type: 'BILLS_PAYMENT',
    amount: 3450.50,
    fee: 25,
    total: 3475.50,
    status: 'COMPLETED',
    referenceNo: 'MERALCO-29102-A',
    notes: 'Meralco electric bill payment for commercial account.',
    createdAt: '2026-10-03T08:22:15Z',
    completedAt: '2026-10-03T08:24:00Z',
  },
  {
    id: 'txn_04',
    transactionNo: 'TXN-20261003-000104',
    customerId: 'cus_04',
    branchId: 'br_04',
    employeeId: 'emp_08',
    type: 'PAWN_LOAN',
    amount: 18000,
    fee: 360,
    total: 18360,
    status: 'PENDING',
    referenceNo: 'PAWN-TKT-7712',
    notes: '18K Yellow Gold Necklace collateral valuation. Over ₱10,000 threshold requires approval.',
    requiresApproval: true,
    approvalId: 'app_02',
    createdAt: '2026-10-03T08:35:00Z',
  },
  {
    id: 'txn_05',
    transactionNo: 'TXN-20261003-000105',
    customerId: 'cus_06',
    branchId: 'br_01',
    employeeId: 'emp_04',
    type: 'REMITTANCE_PAYOUT',
    amount: 6200,
    fee: 0,
    total: 6200,
    status: 'COMPLETED',
    referenceNo: 'ML-PAYOUT-3310',
    notes: 'Verified ID match and secret code confirmation.',
    createdAt: '2026-10-03T08:40:00Z',
    completedAt: '2026-10-03T08:43:10Z',
  },
  {
    id: 'txn_06',
    transactionNo: 'TXN-20261002-000098',
    customerId: 'cus_05',
    branchId: 'br_07',
    employeeId: 'emp_01',
    type: 'WALLET_CASHOUT',
    amount: 12000,
    fee: 120,
    total: 12120,
    status: 'REJECTED',
    referenceNo: 'WAL-OUT-99120',
    notes: 'Rejected by Area Manager: Customer KYC verification incomplete for amount exceeding ₱10,000.',
    createdAt: '2026-10-02T15:20:00Z',
    completedAt: '2026-10-02T15:45:00Z',
  },
  {
    id: 'txn_07',
    transactionNo: 'TXN-20261002-000095',
    customerId: 'cus_01',
    branchId: 'br_02',
    employeeId: 'emp_04',
    type: 'INSURANCE_PREMIUM',
    amount: 150,
    fee: 10,
    total: 160,
    status: 'COMPLETED',
    referenceNo: 'INS-POL-1092',
    notes: 'Accident Protector 30-day coverage policy issuance.',
    createdAt: '2026-10-02T11:15:00Z',
    completedAt: '2026-10-02T11:16:45Z',
  },
  {
    id: 'txn_08',
    transactionNo: 'TXN-20261002-000092',
    customerId: 'cus_02',
    branchId: 'br_03',
    employeeId: 'emp_03',
    type: 'REMITTANCE_SEND',
    amount: 25000,
    fee: 350,
    total: 25350,
    status: 'COMPLETED',
    referenceNo: 'REF-CEB-881900',
    notes: 'Approved by Branch Manager Roberto Tan on 2026-10-02.',
    createdAt: '2026-10-02T09:40:00Z',
    completedAt: '2026-10-02T10:05:00Z',
  },
];

export const INITIAL_APPROVALS: Approval[] = [
  {
    id: 'app_01',
    transactionId: 'txn_02',
    transactionNo: 'TXN-20261003-000102',
    requesterId: 'usr_teller',
    requesterName: 'Ana Reyes (Teller)',
    branchId: 'br_01',
    branchName: 'Cebu Main Operations Hub',
    amount: 45000,
    status: 'PENDING',
    reason: 'Single Foreign Exchange transaction volume exceeds branch teller limit (₱10,000.00). Requires Manager verification of USD bills and serial numbers.',
    createdAt: '2026-10-03T08:10:00Z',
  },
  {
    id: 'app_02',
    transactionId: 'txn_04',
    transactionNo: 'TXN-20261003-000104',
    requesterId: 'usr_admin',
    requesterName: 'Miguel Bautista (Teller)',
    branchId: 'br_04',
    branchName: 'Makati Ayala CBD Branch',
    amount: 18000,
    status: 'PENDING',
    reason: 'Pawn appraisal valuation exceeds ₱10,000 threshold. Gold karat test and weight verification confirmed.',
    createdAt: '2026-10-03T08:35:00Z',
  },
  {
    id: 'app_03',
    transactionId: 'txn_08',
    transactionNo: 'TXN-20261002-000092',
    requesterId: 'usr_teller',
    requesterName: 'Ana Reyes (Teller)',
    approverId: 'usr_branch',
    approverName: 'Roberto Tan (Branch Manager)',
    branchId: 'br_03',
    branchName: 'Colon Heritage Branch',
    amount: 25000,
    status: 'APPROVED',
    reason: 'Remittance exceeding ₱10,000 daily threshold.',
    decisionNote: 'Customer verified with valid Passport. AML checks passed.',
    createdAt: '2026-10-02T09:40:00Z',
    decidedAt: '2026-10-02T10:04:12Z',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_01',
    userId: 'usr_branch',
    title: 'Approval Required: High-Value FX',
    message: 'Transaction TXN-20261003-000102 (₱45,000.00) submitted by Ana Reyes requires authorization.',
    status: 'UNREAD',
    link: '/dashboard/approvals',
    createdAt: '2026-10-03T08:10:05Z',
  },
  {
    id: 'notif_02',
    userId: 'usr_admin',
    title: 'Security Alert: Failed Logins Detected',
    message: 'User EMP00008 reached 5 consecutive failed password attempts. Account locked temporarily.',
    status: 'UNREAD',
    link: '/dashboard/security',
    createdAt: '2026-10-03T08:05:00Z',
  },
  {
    id: 'notif_03',
    userId: 'usr_super',
    title: 'System Notice: Daily Reconciliation Ready',
    message: 'Automated end-of-day operational summary generated for 7 active branches.',
    status: 'READ',
    link: '/dashboard/reports',
    createdAt: '2026-10-02T22:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_01',
    userId: 'usr_super',
    username: 'superadmin',
    action: 'LOGIN',
    module: 'AUTH',
    recordId: 'usr_super',
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    result: 'SUCCESS',
    createdAt: '2026-10-03T08:45:10Z',
  },
  {
    id: 'aud_02',
    userId: 'usr_teller',
    username: 'EMP00004',
    employeeId: 'emp_04',
    action: 'CREATE_TRANSACTION',
    module: 'TRANSACTION',
    recordId: 'txn_02',
    newValue: { transactionNo: 'TXN-20261003-000102', amount: 45000, type: 'FOREIGN_EXCHANGE', status: 'PENDING' },
    ipAddress: '10.12.1.44',
    userAgent: 'Mozilla/5.0 (Branch Terminal OS)',
    result: 'SUCCESS',
    createdAt: '2026-10-03T08:10:00Z',
  },
  {
    id: 'aud_03',
    userId: 'usr_branch',
    username: 'EMP00003',
    employeeId: 'emp_03',
    action: 'APPROVE_TRANSACTION',
    module: 'APPROVAL',
    recordId: 'txn_08',
    oldValue: { status: 'PENDING' },
    newValue: { status: 'COMPLETED', decisionNote: 'Customer verified with valid Passport. AML checks passed.' },
    ipAddress: '10.12.1.2',
    userAgent: 'Mozilla/5.0 (Branch Manager Workstation)',
    result: 'SUCCESS',
    createdAt: '2026-10-02T10:04:12Z',
  },
  {
    id: 'aud_04',
    userId: 'usr_admin',
    username: 'EMP00006',
    employeeId: 'emp_06',
    action: 'UPDATE_SYSTEM_SETTINGS',
    module: 'SETTINGS',
    recordId: 'settings_core',
    oldValue: { approvalThresholdAmount: 8000 },
    newValue: { approvalThresholdAmount: 10000 },
    ipAddress: '10.0.4.15',
    userAgent: 'Mozilla/5.0 (Enterprise Console)',
    result: 'SUCCESS',
    createdAt: '2026-10-01T14:20:00Z',
  },
  {
    id: 'aud_05',
    userId: 'usr_admin',
    username: 'EMP00006',
    employeeId: 'emp_06',
    action: 'LOCK_USER_ACCOUNT',
    module: 'USER',
    recordId: 'usr_locked',
    oldValue: { status: 'ACTIVE', failedAttempts: 4 },
    newValue: { status: 'LOCKED', failedAttempts: 5, lockedUntil: '2026-10-03T18:00:00Z' },
    ipAddress: '10.0.4.15',
    userAgent: 'Security Daemon v2.1',
    result: 'SUCCESS',
    createdAt: '2026-09-30T10:15:00Z',
  },
];

export const INITIAL_LOGIN_LOGS: LoginLog[] = [
  {
    id: 'log_01',
    userId: 'usr_super',
    username: 'superadmin',
    success: true,
    ipAddress: '192.168.1.10',
    userAgent: 'Chrome 128.0 (Windows)',
    createdAt: '2026-10-03T08:45:10Z',
  },
  {
    id: 'log_02',
    userId: 'usr_branch',
    username: 'EMP00003',
    success: true,
    ipAddress: '10.12.1.2',
    userAgent: 'Chrome 128.0 (Windows)',
    createdAt: '2026-10-03T08:15:30Z',
  },
  {
    id: 'log_03',
    userId: 'usr_teller',
    username: 'EMP00004',
    success: true,
    ipAddress: '10.12.1.44',
    userAgent: 'Chrome 128.0 (Windows)',
    createdAt: '2026-10-03T08:00:00Z',
  },
  {
    id: 'log_04',
    username: 'EMP00008',
    success: false,
    reason: 'Invalid credentials entered (Attempt 5 of 5)',
    ipAddress: '10.14.2.89',
    userAgent: 'Chrome 128.0 (Windows)',
    createdAt: '2026-09-30T10:14:55Z',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  organizationName: 'Zebra Enterprise Operations Platform',
  approvalThresholdAmount: 10000,
  dailyBranchLimit: 2500000,
  sessionTimeoutMinutes: 30,
  requireTwoFactorForManagers: true,
  maintenanceMode: false,
  allowWeekendTransactions: true,
  defaultCurrency: 'PHP',
};
